# Generated by Django 5.0.7 on 2026-09-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0004_alter_scanjob_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoasset',
            name='family',
            field=models.CharField(choices=[('rsa', 'RSA'), ('ecc', 'ECC'), ('dsa', 'DSA'), ('dh', 'Diffie-Hellman'), ('aes', 'AES'), ('des3', 'DES/Triple DES'), ('hash', 'Hash'), ('mac', 'MAC'), ('pqc', 'Post-Quantum'), ('unknown', 'Unknown')], max_length=16),
        ),
        migrations.AlterField(
            model_name='normalizedfinding',
            name='family',
            field=models.CharField(choices=[('rsa', 'RSA'), ('ecc', 'ECC'), ('dsa', 'DSA'), ('dh', 'Diffie-Hellman'), ('aes', 'AES'), ('des3', 'DES/Triple DES'), ('hash', 'Hash'), ('mac', 'MAC'), ('pqc', 'Post-Quantum'), ('unknown', 'Unknown')], max_length=16),
        ),
    ]
