# Generated by Django 5.0.7 on 2026-09-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0005_alter_cryptoasset_family_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='error_action',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='error_code',
            field=models.CharField(blank=True, default='', max_length=48),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='error_recoverable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='error_scope',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='items_scanned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='items_skipped',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='items_total',
            field=models.PositiveIntegerField(blank=True, help_text='Items discovered to inspect; null when not yet known.', null=True),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='progress_stage',
            field=models.CharField(blank=True, default='', help_text='Current phase, e.g. enumerating/inspecting/persisting/correlating.', max_length=32),
        ),
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
