# Generated by Django 5.0.7 on 2026-09-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0006_scanjob_error_action_scanjob_error_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalizedfinding',
            name='evidence',
            field=models.JSONField(blank=True, default=dict, help_text='Why ECDAT believes this exists. Never contains secret material.'),
        ),
        migrations.AddField(
            model_name='normalizedfinding',
            name='kind',
            field=models.CharField(choices=[('algorithm', 'Algorithm'), ('key', 'Key'), ('certificate', 'Certificate'), ('protocol', 'Protocol'), ('library', 'Library'), ('dependency', 'Dependency'), ('crypto_api', 'Crypto API'), ('crypto_configuration', 'Crypto configuration'), ('key_reference', 'Key reference'), ('hardware_module', 'Hardware module'), ('cloud_crypto_service', 'Cloud crypto service'), ('unknown_crypto_artifact', 'Unknown artefact')], default='algorithm', help_text='Category of cryptographic artefact observed.', max_length=32),
        ),
        migrations.AddField(
            model_name='normalizedfinding',
            name='line',
            field=models.PositiveIntegerField(blank=True, help_text='Line within the located file, when known.', null=True),
        ),
    ]
