# Generated by Django 5.0.7 on 2026-09-27 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
        ('discovery', '0007_normalizedfinding_evidence_normalizedfinding_kind_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.CharField(max_length=256)),
                ('version', models.CharField(blank=True, default='', max_length=64)),
                ('ecosystem', models.CharField(blank=True, default='', max_length=32)),
                ('scope', models.CharField(choices=[('runtime', 'Runtime'), ('development', 'Development')], default='runtime', max_length=16)),
                ('is_crypto', models.BooleanField(default=False)),
                ('relevance', models.CharField(blank=True, choices=[('core', 'Core crypto'), ('supporting', 'Supporting'), ('adjacent', 'Adjacent'), ('managed_key_service', 'Managed key service'), ('post_quantum', 'Post-quantum')], default='', max_length=32)),
                ('capability', models.CharField(blank=True, default='', max_length=64)),
                ('key_service', models.CharField(blank=True, default='', help_text='Managed key service, e.g. aws/azure.', max_length=32)),
                ('family', models.CharField(choices=[('rsa', 'RSA'), ('ecc', 'ECC'), ('dsa', 'DSA'), ('dh', 'Diffie-Hellman'), ('aes', 'AES'), ('des3', 'DES/Triple DES'), ('hash', 'Hash'), ('mac', 'MAC'), ('pqc', 'Post-Quantum'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('location', models.CharField(blank=True, default='', help_text='Manifest this came from.', max_length=1024)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('scan_job', models.ForeignKey(blank=True, help_text='Scan that discovered this dependency.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='discovery.scanjob')),
                ('session', models.ForeignKey(blank=True, help_text='Work session this dependency belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.worksession')),
            ],
            options={
                'ordering': ['package', 'version'],
                'indexes': [models.Index(fields=['ecosystem', 'package'], name='discovery_d_ecosyst_9fe2f1_idx'), models.Index(fields=['is_crypto', 'relevance'], name='discovery_d_is_cryp_4fea65_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='dependency',
            constraint=models.UniqueConstraint(fields=('session', 'package', 'ecosystem', 'scope', 'location'), name='uniq_dependency_per_manifest'),
        ),
    ]
