# Generated by Django 5.0.7 on 2026-09-27 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
        ('discovery', '0008_dependency_dependency_uniq_dependency_per_manifest'),
    ]

    operations = [
        migrations.CreateModel(
            name='DependencyRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('depends_on', 'Depends on'), ('provides', 'Provides')], max_length=16)),
                ('detail', models.CharField(blank=True, default='', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_dependency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='discovery.dependency')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependency_relations', to='core.worksession')),
                ('to_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependency_relations', to='discovery.cryptoasset')),
                ('to_dependency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='discovery.dependency')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='dependencyrelation',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('to_asset__isnull', True), ('to_dependency__isnull', False)), models.Q(('to_asset__isnull', False), ('to_dependency__isnull', True)), _connector='OR'), name='dep_rel_exactly_one_target'),
        ),
        migrations.AddConstraint(
            model_name='dependencyrelation',
            constraint=models.UniqueConstraint(fields=('from_dependency', 'to_dependency', 'relation_type'), name='uniq_dep_rel_dependency'),
        ),
        migrations.AddConstraint(
            model_name='dependencyrelation',
            constraint=models.UniqueConstraint(fields=('from_dependency', 'to_asset', 'relation_type'), name='uniq_dep_rel_asset'),
        ),
    ]
