# Generated by Django 5.0.7 on 2026-09-27 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
        ('discovery', '0009_dependencyrelation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, default='', max_length=1024)),
                ('line', models.PositiveIntegerField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('evidence', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='asset_type',
            field=models.CharField(choices=[('application', 'Application'), ('repository', 'Repository'), ('source_code', 'Source code'), ('binary', 'Binary'), ('firmware', 'Firmware'), ('container', 'Container'), ('library', 'Library'), ('dependency', 'Dependency'), ('certificate', 'Certificate'), ('key_reference', 'Key reference'), ('cloud_resource', 'Cloud resource'), ('infrastructure', 'Infrastructure'), ('hardware', 'Hardware'), ('network_endpoint', 'Network endpoint'), ('external_service', 'External service'), ('api', 'API'), ('unknown', 'Unknown')], default='unknown', help_text='Category of the thing carrying this cryptography.', max_length=32),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='environment',
            field=models.CharField(blank=True, default='', help_text='Deployment environment when the scanner can determine it.', max_length=64),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='identifier',
            field=models.CharField(blank=True, default='', help_text='Stable content-derived identity for this artefact.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='cryptoasset',
            index=models.Index(fields=['asset_type'], name='discovery_c_asset_t_4df4d3_idx'),
        ),
        migrations.AddField(
            model_name='assetoccurrence',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='discovery.cryptoasset'),
        ),
        migrations.AddField(
            model_name='assetoccurrence',
            name='finding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='discovery.normalizedfinding'),
        ),
        migrations.AddField(
            model_name='assetoccurrence',
            name='scan_job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_occurrences', to='discovery.scanjob'),
        ),
        migrations.AddIndex(
            model_name='assetoccurrence',
            index=models.Index(fields=['asset', 'location'], name='discovery_a_asset_i_e6c460_idx'),
        ),
    ]
