# Generated by Django 5.0.7 on 2026-09-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0010_assetoccurrence_cryptoasset_asset_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='skip_reasons',
            field=models.JSONField(blank=True, default=dict, help_text="Per-reason breakdown of skipped items, e.g. {'unreadable': 3, 'unrecognised_format': 1}. Explains why a scan reported partial coverage."),
        ),
    ]
