# Generated by Django 5.0.7 on 2026-09-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0011_scanjob_skip_reasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedfinding',
            name='kind',
            field=models.CharField(choices=[('algorithm', 'Algorithm'), ('key', 'Key'), ('certificate', 'Certificate'), ('protocol', 'Protocol'), ('library', 'Library'), ('dependency', 'Dependency'), ('crypto_api', 'Crypto API'), ('crypto_configuration', 'Crypto configuration'), ('key_reference', 'Key reference'), ('hardware_module', 'Hardware module'), ('cloud_crypto_service', 'Cloud crypto service'), ('container', 'Container image'), ('unknown_crypto_artifact', 'Unknown artefact')], default='algorithm', help_text='Category of cryptographic artefact observed.', max_length=32),
        ),
    ]
