# Generated by Django 5.0.7 on 2026-09-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
        ('discovery', '0012_alter_normalizedfinding_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target', models.CharField(max_length=512)),
                ('scan_type', models.CharField(default='specified', max_length=16)),
                ('source_types', models.JSONField(blank=True, default=list, help_text='The sources the user asked for, in the order they were listed.')),
                ('excluded', models.JSONField(blank=True, default=list, help_text="Sources that were not run, with the reason, e.g. [{'source': 'binary', 'reason': 'needs a folder target'}].")),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('validating', 'Validating'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0)),
                ('mode', models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_batches', to='core.worksession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scanjob',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Parent run when this job is one source of a multi-source scan.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='discovery.scanbatch'),
        ),
        migrations.AddIndex(
            model_name='scanbatch',
            index=models.Index(fields=['status'], name='discovery_s_status_00d450_idx'),
        ),
        migrations.AddIndex(
            model_name='scanbatch',
            index=models.Index(fields=['mode'], name='discovery_s_mode_b07aa4_idx'),
        ),
    ]
