# Generated by Django 5.0.7 on 2026-09-27 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0013_scanbatch_scanjob_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanbatch',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scanbatch',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
