# Generated by Django 5.0.7 on 2026-09-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0014_scanbatch_finished_at_scanbatch_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text='Absolute path the asset was read from, when read from disk.', max_length=1024),
        ),
        migrations.AddField(
            model_name='dependency',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text='Absolute path of the manifest, used to locate lock files beside it.', max_length=1024),
        ),
        migrations.AddField(
            model_name='rawfinding',
            name='source_path',
            field=models.CharField(blank=True, default='', help_text='Absolute filesystem path the scanner actually read. Lets post-ingest steps re-open the artefact without guessing from the display label.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Display label for the place this asset was seen.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='dependency',
            name='location',
            field=models.CharField(blank=True, default='', help_text='Display label of the manifest this came from.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='rawfinding',
            name='location',
            field=models.CharField(blank=True, default='', help_text="Human-readable location shown in the UI. In a quick or whole scan this is a profile label such as 'WORKSPACE/package.json', not a filesystem path.", max_length=1024),
        ),
    ]
