# Generated by Django 5.0.7 on 2026-09-27 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_apikey'),
        ('discovery', '0015_cryptoasset_source_path_dependency_source_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('application', 'Application'), ('repository', 'Repository'), ('container', 'Container'), ('file', 'File'), ('api', 'API'), ('library', 'Library'), ('dependency', 'Dependency'), ('algorithm', 'Algorithm'), ('key', 'Key'), ('certificate', 'Certificate'), ('protocol', 'Protocol'), ('endpoint', 'Endpoint'), ('infrastructure', 'Infrastructure')], max_length=20)),
                ('key', models.CharField(help_text="Stable identity within the type, e.g. 'file:C:/app/x.py'.", max_length=512)),
                ('label', models.CharField(blank=True, default='', max_length=256)),
                ('ref_model', models.CharField(blank=True, default='', max_length=32)),
                ('ref_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('family', models.CharField(blank=True, default='', max_length=16)),
                ('algorithm', models.CharField(blank=True, default='', max_length=64)),
                ('asset_type', models.CharField(blank=True, default='', max_length=32)),
                ('source_type', models.CharField(blank=True, default='', max_length=16)),
                ('location', models.CharField(blank=True, default='', max_length=1024)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(blank=True, help_text='Work session this node belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_nodes', to='core.worksession')),
            ],
            options={
                'ordering': ['node_type', 'label', 'key'],
            },
        ),
        migrations.CreateModel(
            name='GraphEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('contains', 'Contains'), ('uses', 'Uses'), ('depends_on', 'Depends on'), ('provides', 'Provides'), ('signed_by', 'Signed by'), ('exposes', 'Exposes'), ('implements', 'Implements'), ('co_located', 'Co-located'), ('relates_to', 'Relates to')], max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('confidence', models.FloatField(default=1.0)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='graph_edges', to='core.worksession')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='discovery.graphnode')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='discovery.graphnode')),
            ],
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['node_type'], name='discovery_g_node_ty_6a3b9e_idx'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['session', 'node_type'], name='discovery_g_session_7995be_idx'),
        ),
        migrations.AddIndex(
            model_name='graphnode',
            index=models.Index(fields=['key'], name='discovery_g_key_e746e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphnode',
            constraint=models.UniqueConstraint(fields=('session', 'node_type', 'key'), name='uniq_graph_node_per_session'),
        ),
        migrations.AddIndex(
            model_name='graphedge',
            index=models.Index(fields=['relation_type'], name='discovery_g_relatio_ed0ca9_idx'),
        ),
        migrations.AddIndex(
            model_name='graphedge',
            index=models.Index(fields=['from_node', 'relation_type'], name='discovery_g_from_no_aece75_idx'),
        ),
        migrations.AddIndex(
            model_name='graphedge',
            index=models.Index(fields=['to_node', 'relation_type'], name='discovery_g_to_node_148fa2_idx'),
        ),
        migrations.AddConstraint(
            model_name='graphedge',
            constraint=models.UniqueConstraint(fields=('from_node', 'to_node', 'relation_type'), name='uniq_graph_edge'),
        ),
    ]
