# Generated by Django 5.0.7 on 2026-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_analysisrun_awaituntil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('awaiting_context', 'Awaiting context'), ('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
