# Generated by Django 5.0.7 on 2026-09-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_alter_analysisrun_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='status',
            field=models.CharField(choices=[('awaiting_context', 'Awaiting context'), ('queued', 'Queued'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
