# 
"""
Drops the `mode` column and its indexes.

Demo mode is removed. `mode` existed to label rows as synthetic (demo) or real
(actual) and to pair with the second `demo` database that enforced the split at
the schema level. With one database and no demo boundary, the column was always
"actual" and asserted nothing -- it was a label that could disagree with the
database it sat in, which is worse than having no label at all.

The values are intentionally discarded rather than migrated: no code path reads
this column any more, so preserving "actual" on every row would be dead data.
"""

# Generated by Django 5.0.7 on 2026-09-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_alter_analysisrun_status'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysisrun',
            name='analysis_an_mode_53d302_idx',
        ),
        migrations.RemoveIndex(
            model_name='assetassessment',
            name='analysis_as_mode_b89e32_idx',
        ),
        migrations.RemoveField(
            model_name='analysisrun',
            name='mode',
        ),
        migrations.RemoveField(
            model_name='assetassessment',
            name='mode',
        ),
    ]
