# Generated by Django 5.0.7 on 2026-09-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_remove_analysisrun_analysis_an_mode_53d302_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='coverage',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
