# Generated by Django 5.0.7 on 2026-09-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_analysisrun_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisrun',
            name='coverage',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
