"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if present
load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-yx1_&c3=7vr**k96qhk66sr*t1%8bhmp__&_hp50^61uztm76c')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', '1') == '1'

if DEBUG:
    ALLOWED_HOSTS = ['*']
else:
    ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local apps — organised into workstream segments (see docs/architecture).
    'core',
    'segments.scraping.discovery',
    'segments.scraping.crypto_scan',
    'segments.ml.analysis',
    'segments.mitigation.mitigation',
    'segments.reporting.dashboard',
    'segments.reporting.reports',
]

MIDDLEWARE = [
    'core.api.EnvelopeMiddleware',
    'core.api.ApiKeyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'core.middleware.WorkSessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

FRONTEND_ORIGINS = [
    origin.strip().rstrip('/')
    for origin in os.getenv(
        'ECDAT_FRONTEND_ORIGINS',
        'http://localhost:3000,http://127.0.0.1:3000',
    ).split(',')
    if origin.strip()
]
CORS_ALLOWED_ORIGINS = FRONTEND_ORIGINS
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = FRONTEND_ORIGINS

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# SQLite is single-writer. A multi-source discovery run writes from several
# scanner threads at once, and without a wait the loser of the race gets an
# immediate "database is locked" and the scan fails outright.
#
# `timeout` is the only OPTIONS key the plain (non-pooled) sqlite backend
# accepts on Django 5.0; WAL and busy_timeout are applied per connection by
# core.sqlite_pragmas, which is the only supported way to set them here.
_SQLITE_WRITE_OPTIONS = {
    "timeout": 30,          # seconds to wait for a competing writer
}

DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        'USER': os.getenv('DB_USER', ''),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', ''),
        'PORT': os.getenv('DB_PORT', ''),
        'OPTIONS': dict(_SQLITE_WRITE_OPTIONS),
    },
    'demo': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': BASE_DIR / 'demo.sqlite3',
        'OPTIONS': dict(_SQLITE_WRITE_OPTIONS),
    },
}

# Route reads/writes/migrations by the active mode for a hard demo/actual
# data boundary (see config/db_router.py and core/modes.py).
DATABASE_ROUTERS = ['config.db_router.ECDATRouter']


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'COERCE_DECIMAL_TO_STRING': False,
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ECDAT configuration
# API-key enforcement: explicit ECDAT_REQUIRE_API_KEY wins; otherwise enabled
# whenever DEBUG is off (production) and disabled in development/tests.
_require_api_key = os.getenv('ECDAT_REQUIRE_API_KEY')
if _require_api_key is None:
    _require_api_key = '0' if DEBUG else '1'

ECDAT = {
    'DEMO_MODE': os.getenv('ECDAT_DEMO_MODE', '1') == '1',
    # The active data boundary: 'demo' (synthetic) or 'actual' (real).
    # All reads/writes route to the matching database.
    'ACTIVE_MODE': os.getenv('ECDAT_ACTIVE_MODE', 'demo'),
    # When true, every /api/ route (except health) requires a valid API key.
    'REQUIRE_API_KEY': _require_api_key == '1',
}

# Huey task queue (SqliteHuey). Load after ECDAT so env defaults are ready.
from segments.scraping.crypto_scan.hueyconf import HUEY as _HUEY  # noqa: E402
HUEY = _HUEY
