#!/usr/bin/env bash
#
# ECDAT — full automated setup for Enterprise Cryptographic Discovery & Analysis Tool
#
# Cross-platform (Linux, macOS, and Git-Bash / WSL on Windows).
# - Creates & activates a virtual environment
# - Installs Python + Node (Tailwind) dependencies
# - Sets up .env from .env.example (with a generated secret key)
# - Runs migrations on both the 'actual' (db.sqlite3) and 'demo' (demo.sqlite3) DBs
# - Seeds demo data
# - Runs several checks and reports whether everything is good
#
# Usage:
#   bash setup.sh            # non-interactive, full default setup
#   bash setup.sh --skip-seed  # skip demo seeding
#   bash setup.sh --help
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Pretty printing + helpers
# ---------------------------------------------------------------------------
RED=$'\033[0;31m'; GREEN=$'\033[0;32m'; YELLOW=$'\033[1;33m'; CYAN=$'\033[0;36m'; BOLD=$'\033[1m'; RESET=$'\033[0m'

info()  { echo "${CYAN}── ${BOLD}$*${RESET}"; }
step()  { echo ""; echo "${GREEN}==> $*${RESET}"; }
warn()  { echo "${YELLOW}WARN: $*${RESET}"; }
fail()  { echo "${RED}ERROR: $*${RESET}"; }
ok()    { echo "${GREEN}OK: $*${RESET}"; }

SEED_DEMO=1
for arg in "$@"; do
  case "$arg" in
    --skip-seed) SEED_DEMO=0 ;;
    --help|-h)
      echo "ECDAT setup.sh"
      echo "  bash setup.sh            full default setup + demo seed + checks"
      echo "  bash setup.sh --skip-seed  skip the demo-data seeding"
      exit 0
      ;;
  esac
done

# Root directory of the project (repo root = where this script lives)
ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

info "ECDAT setup running in: $ROOT_DIR"

# ---------------------------------------------------------------------------
# Platform detection (Unix vs Windows Git-Bash/WSL)
# ---------------------------------------------------------------------------
IS_WINDOWS=0
case "$(uname -s)" in
  MINGW*|MSYS*|CYGWIN*|*WSL*) IS_WINDOWS=1 ;;
esac

if [ "$IS_WINDOWS" = "1" ]; then
  PY="python"
  VENV_PY="$ROOT_DIR/venv/Scripts/python.exe"
  VENV_ACT="$ROOT_DIR/venv/Scripts/Activate.ps1"
  # Allow the py launcher if plain `python` is not present
  command -v "$PY" >/dev/null 2>&1 || PY="py -3"
else
  PY="python3"
  VENV_PY="$ROOT_DIR/venv/bin/python"
  VENV_ACT="$ROOT_DIR/venv/bin/activate"
fi

# ---------------------------------------------------------------------------
# 1. Prerequisites
# ---------------------------------------------------------------------------
step "Checking prerequisites"

if ! command -v "$PY" >/dev/null 2>&1; then
  fail "Python not found. Install Python 3.12+ and re-run. (searched for: $PY)"
  exit 1
fi
PYVER="$("$PY" --version 2>&1 || true)"
echo "  $PYVER"

if ! command -v npm >/dev/null 2>&1; then
  fail "npm not found. Install Node.js 18+ and re-run."
  exit 1
fi
echo "  $(npm --version 2>/dev/null | sed 's/^/npm /' || true) / node $(node --version 2>/dev/null | sed 's/^v//' || echo '?')"

# ---------------------------------------------------------------------------
# 2. Virtual environment
# ---------------------------------------------------------------------------
step "Virtual environment"

if [ -x "$VENV_PY" ]; then
  ok "virtual environment already present: $VENV_PY"
else
  info "creating venv..."
  "$PY" -m venv venv
  if [ ! -x "$VENV_PY" ]; then
    fail "Failed to create venv (tried the '$VENV_PY' layout)."
    exit 1
  fi
  ok "created: $VENV_PY"
fi

# ---------------------------------------------------------------------------
# 3. Environment variables (.env)
# ---------------------------------------------------------------------------
step "Environment variables"

if [ -f "$ROOT_DIR/.env" ]; then
  ok ".env already exists — leaving it untouched. Review it before production:"
else
  info "creating .env from .env.example with a generated secret key..."
  # Generate a strong random Django secret key
  if command -v openssl >/dev/null 2>&1; then
    SECRET="$(openssl rand -base64 48 | tr -d '\n=' )"
  else
    SECRET="$(head -c 32 /dev/urandom | base64 | tr -d '\n=' || printf 'dev-%s' "$(date +%s)")"
  fi
  cat > "$ROOT_DIR/.env" <<EOF
# ECDAT environment (auto-generated by setup.sh — edit to suit).
DJANGO_SECRET_KEY=$SECRET
DJANGO_DEBUG=1
DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost

# Active data boundary: 'demo' (synthetic) or 'actual' (real).
# Selects the live database (demo -> demo.sqlite3, actual -> db.sqlite3).
ECDAT_ACTIVE_MODE=demo

# Enables the demo dataset/seed for the demo boundary.
ECDAT_DEMO_MODE=1

# Optional PostgreSQL (also requires enabling in config/settings.py + psycopg2)
# DB_ENGINE=django.db.backends.postgresql
# DB_NAME=ecdat
# DB_USER=ecdat
# DB_PASSWORD=change_me
# DB_HOST=127.0.0.1
# DB_PORT=5432
EOF
  ok "created .env with a generated DJANGO_SECRET_KEY"
fi

cat <<'ENVHELP'
  Key variables (edit .env when needed):
    DJANGO_SECRET_KEY   secret (a random one was generated for you)
    DJANGO_DEBUG        '1' for development, '0' for live
    DJANGO_ALLOWED_HOSTS  only used when DEBUG=0 (comma separated)
    ECDAT_ACTIVE_MODE   'demo' -> demo.sqlite3, 'actual' -> db.sqlite3
    ECDAT_DEMO_MODE     '1' enables demo datasets / seed command
ENVHELP

# ---------------------------------------------------------------------------
# 4. Install Python dependencies
# ---------------------------------------------------------------------------
step "Installing Python dependencies"
"$VENV_PY" -m pip install --upgrade pip
"$VENV_PY" -m pip install -r requirements.txt
ok "Python dependencies installed"

# ---------------------------------------------------------------------------
# 5. Install Node dependencies + build Tailwind CSS
# ---------------------------------------------------------------------------
step "Installing frontend tooling and building Tailwind CSS"
if [ ! -f "$ROOT_DIR/package-lock.json" ]; then
  npm install
else
  npm ci || npm install
fi
npm run build
ok "Tailwind CSS built (dashboard/static/dashboard/css/tailwind.css)"
if [ "$IS_WINDOWS" = "1" ]; then
  echo "  tip: during development run 'npm run watch' to auto-rebuild"
fi

# ---------------------------------------------------------------------------
# 6. Migrations (both 'default' and 'demo' databases)
# ---------------------------------------------------------------------------
step "Running database migrations (actual + demo)"
"$VENV_PY" manage.py makemigrations
"$VENV_PY" manage.py migrate
# The router runs migrations on both DBs, but be explicit as a fail-safe.
"$VENV_PY" manage.py migrate --database default || true
"$VENV_PY" manage.py migrate --database demo || true
ok "Migrations applied"

# ---------------------------------------------------------------------------
# 7. Seed demo data (optional)
# ---------------------------------------------------------------------------
if [ "$SEED_DEMO" = "1" ]; then
  step "Seeding demo data"
  if "$VENV_PY" manage.py seed_demo; then
    ok "demo data seeded"
  else
    warn "seed_demo did not run. Demo seeding requires ECDAT_ACTIVE_MODE=demo and"
    warn "ECDAT_DEMO_MODE=1 in .env. Set those and run 'manage.py seed_demo' when ready."
  fi
else
  step "Skipping demo seeding (--skip-seed)"
fi

# ---------------------------------------------------------------------------
# 8. Checks — report if everything is good
# ---------------------------------------------------------------------------
step "Running checks"
FAILURES=0

echo "${BOLD}-- Django system check --${RESET}"
if "$VENV_PY" manage.py check; then ok "manage.py check passes"; else fail "manage.py check FAILED"; FAILURES=1; fi

echo ""
echo "${BOLD}-- Tailwind CSS build check --${RESET}"
if npm run build; then ok "Tailwind build passes"; else fail "Tailwind build FAILED"; FAILURES=1; fi

echo ""
echo "${BOLD}-- Dashboard page render check (Django test client) --${RESET}"
CHECK_PY="$ROOT_DIR/.ecdat_rendercheck.py"
cat > "$CHECK_PY" <<'PYEOF'
import os, django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'config.settings')
django.setup()
from django.test import Client
c = Client()
c.defaults['HTTP_HOST'] = '127.0.0.1'
routes = [('/', 'Overview'), ('/discovery/', 'Discovery'), ('/inventory/', 'Inventory'),
          ('/graph/', 'Asset Graph'), ('/risk/', 'Risk & Reasoning'),
          ('/mitigation/', 'Mitigation'), ('/reports/', 'Reports'), ('/audit/', 'Audit Log')]
bads = []
for path, name in routes:
    code = c.get(path).status_code
    if code != 200:
        bads.append(f"{name} ({path}) -> {code}")
if bads:
    print("FAIL:" + "; ".join(bads))
else:
    print("OK: all 8 workflow pages returned 200")
PYEOF
RENDER_CHECK="$("$VENV_PY" "$CHECK_PY" 2>/dev/null || true)"
rm -f "$CHECK_PY"
echo "$RENDER_CHECK"
if echo "$RENDER_CHECK" | grep -q "^OK:"; then
  ok "all 8 workflow pages return 200"
else
  fail "some pages did not render 200"
  echo "$RENDER_CHECK"
  FAILURES=1
fi

# ---------------------------------------------------------------------------
# 9. Summary
# ---------------------------------------------------------------------------
echo ""
echo "================================================================"
if [ "$FAILURES" = "0" ]; then
  echo "${GREEN}${BOLD}✓ Setup complete — everything checks out.${RESET}"
  echo "================================================================
  Run the server:

  ${BOLD}Activate:${RESET}"
  if [ "$IS_WINDOWS" = "1" ]; then
    echo "    .\\venv\\Scripts\\Activate.ps1        (PowerShell)"
    echo "    or \"$ROOT_DIR/venv/Scripts/python.exe\" manage.py runserver"
  else
    echo "    source $ROOT_DIR/venv/bin/activate"
  fi
  echo "
  ${BOLD}Start:${RESET}
    python manage.py runserver
    -> open  http://127.0.0.1:8000/

  ${BOLD}Optional:${RESET}
    python manage.py createsuperuser   # admin login at /admin"
else
  echo "${RED}${BOLD}✗ Setup finished with failures. Review the messages above.${RESET}"
  echo "================================================================
"
  exit 1
fi
