# Generated by Django 5.0.7 on 2026-08-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8),
        ),
    ]
