"""Mitigation planning: generate prioritized remediation for a finished run.

Sits one step past ``analysis.runner`` — as soon as an AnalysisRun reaches
``completed`` the planner creates a MitigationPlan and hands it to the
mitigation agent suite (blast radius, migration impact, suggestions, optional
Gemini narrator). Follows the runner discipline: DB rows are the source of
truth, the huey task is a thin async wrapper, progress writes stay idempotent
and generation never raises — failures mark the plan failed.
"""

import logging
import os
import threading

from django.conf import settings
from django.utils import timezone
from huey.contrib.djhuey import db_task

from core.models import log_action
from core.modes import active_mode, db_alias_for_mode
from segments.mitigation.mitigation_agent import MitigationAgent

from .models import MitigationPlan

logger = logging.getLogger("mitigation")


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------


def ensure_plan(run, db="default"):
    """Return the (existing or newly created) plan row for a run, atomically."""
    plan, _ = MitigationPlan.objects.using(db).get_or_create(
        run=run,
        defaults={
            "session_id": run.session_id,
            "status": MitigationPlan.Status.PENDING,
            "progress": 0,
        },
    )
    return plan


def trigger_mitigation(run, db="default"):
    """Create a plan for a completed run and dispatch generation.

    Idempotent: a COMPLETE plan is returned untouched; a queued/generating or
    failed plan is re-dispatched so stuck rows recover; a user-cancelled plan
    is reset to pending so the manual "regenerate" actually revives it.
    Returns the plan.
    """
    plan = ensure_plan(run, db)
    if plan.status == MitigationPlan.Status.COMPLETE:
        return plan
    if plan.status == MitigationPlan.Status.CANCELLED:
        plan.status = MitigationPlan.Status.PENDING
        plan.error = ""
        plan.save(using=db, update_fields=["status", "error"])
    log_action(
        "mitigation_queued",
        f"Queued mitigation plan for analysis run {run.pk}",
        "mitigationplan",
        plan.pk,
        session_id=run.session_id,
    )
    _dispatch(plan, db)
    return plan


# ---------------------------------------------------------------------------
# Dispatch (mirrors analysis.runner: thread by default, huey on demand)
# ---------------------------------------------------------------------------


def _dispatch(plan, db):
    mode = active_mode()
    if os.environ.get("ECDAT_QUEUE_ASYNC") == "1":
        generate_plan_task(plan.pk, mode)
    elif settings.HUEY.get("immediate"):
        generate_plan_task(plan.pk, mode)
    else:
        threading.Thread(
            target=_generate_safe,
            args=(plan.pk, mode),
            daemon=True,
        ).start()


def _generate_safe(plan_id, mode):
    from django.db import close_old_connections

    try:
        generate_plan(plan_id, mode)
    except Exception as exc:  # noqa: BLE001 - worker thread must survive
        logger.exception("generate_plan(%s, %s) crashed: %s", plan_id, mode, exc)
        try:
            db = db_alias_for_mode(mode)
            plan = MitigationPlan.objects.using(db).filter(pk=plan_id).first()
            if plan is not None:
                plan.status = MitigationPlan.Status.FAILED
                plan.error = str(exc)
                plan.save(using=db, update_fields=["status", "error"])
        except Exception:
            pass
    finally:
        close_old_connections()


# ---------------------------------------------------------------------------
# Generation pipeline
# ---------------------------------------------------------------------------


def generate_plan(plan_id, mode):
    """Run the mitigation agent suite for a plan and persist the document.

    Never raises: any stage failure marks the plan failed (with error text).
    Returns the plan or None when the row cannot be found.
    """
    db = db_alias_for_mode(mode)
    plan = (
        MitigationPlan.objects.using(db)
        .select_related("run__scan_job")
        .filter(pk=plan_id)
        .first()
    )
    if plan is None:
        logger.warning("generate_plan: plan %s not found in db '%s'", plan_id, db)
        return None

    run = plan.run
    try:
        # Compare-and-swap into GENERATING so a cancelled plan is never
        # resurrected by a stale queued task, and a plan being generated by
        # another executor is never generated twice.
        won = (
            MitigationPlan.objects.using(db)
            .filter(
                pk=plan.pk,
                status__in=[
                    MitigationPlan.Status.PENDING,
                    MitigationPlan.Status.CANCELLED,
                ],
            )
            .update(status=MitigationPlan.Status.GENERATING, progress=15, error="")
        )
        if not won:
            return plan
        plan.status = MitigationPlan.Status.GENERATING
        plan.progress = 15
        plan.error = ""

        bundle = _run_bundle(run, db)
        plan.progress = 30
        plan.save(using=db, update_fields=["progress"])

        if _plan_is_cancelled(plan, db):
            return plan

        document = MitigationAgent().generate(bundle)
        plan.progress = 90
        plan.save(using=db, update_fields=["progress"])

        # Finish only if the plan is still generating — a user cancel that
        # landed while the agent suite ran must win over this completion.
        finished_at = timezone.now()
        won = (
            MitigationPlan.objects.using(db)
            .filter(pk=plan.pk, status=MitigationPlan.Status.GENERATING)
            .update(
                status=MitigationPlan.Status.COMPLETE,
                document=document,
                progress=100,
                generated_at=finished_at,
                error="",
            )
        )
        if not won:
            logger.info("generate_plan: plan %s cancelled mid-generation; leaving cancelled", plan.pk)
            return plan
        plan.document = document
        plan.status = MitigationPlan.Status.COMPLETE
        plan.progress = 100
        plan.generated_at = finished_at
        log_action(
            "mitigation_completed",
            f"Mitigation plan generated for analysis run {run.pk} "
            f"({document['summary']['assets']} assets)",
            "mitigationplan",
            plan.pk,
            session_id=run.session_id,
        )
        return plan
    except Exception as exc:  # noqa: BLE001 - the plan must be marked failed
        won = (
            MitigationPlan.objects.using(db)
            .filter(pk=plan.pk, status=MitigationPlan.Status.GENERATING)
            .update(status=MitigationPlan.Status.FAILED, error=str(exc), progress=0)
        )
        if won:
            log_action(
                "system",
                f"Mitigation plan failed: {exc}",
                "mitigationplan",
                plan.pk,
                session_id=run.session_id,
            )
        return plan


def _plan_is_cancelled(plan, db) -> bool:
    """True once the plan row has been flipped to cancelled (by any request)."""
    return (
        MitigationPlan.objects.using(db)
        .filter(pk=plan.pk, status=MitigationPlan.Status.CANCELLED)
        .exists()
    )


def cancel_plan(plan, db=None) -> bool:
    """Cancel a mitigation plan (compare-and-swap) and return True if it won.

    Only pending/generating plans are cancelled; complete, failed or already
    cancelled plans are left untouched (False). The generating agent thread
    picks the cancelled state up at its next checkpoint (or at completion)
    and leaves the row cancelled.
    """
    db = db or plan._state.db or "default"
    won = (
        MitigationPlan.objects.using(db)
        .filter(
            pk=plan.pk,
            status__in=[MitigationPlan.Status.PENDING, MitigationPlan.Status.GENERATING],
        )
        .update(status=MitigationPlan.Status.CANCELLED, progress=0, error="Cancelled by user")
    )
    if not won:
        return False
    plan.status = MitigationPlan.Status.CANCELLED
    plan.progress = 0
    plan.error = "Cancelled by user"
    log_action("mitigation_cancelled", f"Mitigation plan cancelled by user",
               "mitigationplan", plan.pk, session_id=plan.session_id)
    return True


def sweep_pending_plans() -> int:
    """Re-queue mitigation plans a previous process left unfinished.

    Startup recovery (run_all.sh / run_huey boot): plans stuck PENDING
    (dispatched but never started) and plans stuck GENERATING (process died
    midway) are reset and re-dispatched on the huey queue so the worker
    completes them. Returns the count re-queued.
    """
    from core import modes as modes_mod

    recovered = 0
    for mode in modes_mod.MODES:
        db = modes_mod.db_alias_for_mode(mode)

        for plan in list(
            MitigationPlan.objects.using(db).filter(status=MitigationPlan.Status.PENDING)[:200]
        ):
            log_action("mitigation_requeued", f"Re-queued stuck mitigation plan {plan.pk}",
                       "mitigationplan", plan.pk, session_id=plan.session_id)
            generate_plan_task(plan.pk, active_mode())
            recovered += 1

        for plan in list(
            MitigationPlan.objects.using(db).filter(status=MitigationPlan.Status.GENERATING)[:200]
        ):
            won = (
                MitigationPlan.objects.using(db)
                .filter(pk=plan.pk, status=MitigationPlan.Status.GENERATING)
                .update(status=MitigationPlan.Status.PENDING, progress=0, error="")
            )
            if not won:
                continue
            plan.status = MitigationPlan.Status.PENDING
            plan.progress = 0
            plan.error = ""
            plan.save(using=db, update_fields=["status", "progress", "error"])
            log_action("mitigation_requeued", f"Restarted stuck mitigation plan {plan.pk}",
                       "mitigationplan", plan.pk, session_id=plan.session_id)
            generate_plan_task(plan.pk, active_mode())
            recovered += 1

    return recovered


def _run_bundle(run, db):
    """Assemble the plain-dict bundle the mitigation agents consume.

    Merges canonical CryptoAsset records (or AssetAssessment rows when canonical assets
    are absent) with rich CBOM + HNDL + MOSCA artifacts so the agent suite builds
    prioritized, deduplicated remediation work items directly for canonical assets.
    """
    exec_summary = run.executive_summary or {}
    rows = exec_summary.get("rows") or []
    row_by_asset = {str(row.get("asset_id")): row for row in rows if row.get("asset_id")}
    risk_ctx = run.risk_context or {}
    repository = run.repository or {}
    target = ""
    scan_job = getattr(run, "scan_job", None)
    if scan_job is not None:
        target = scan_job.target or ""
    risk_app = risk_ctx.get("application") or {}
    raw_app = repository.get("name") or risk_app.get("name") or target or "ECDAT inventory"
    from segments.reporting.reports.report_builder import _sanitize_path
    app_name = _sanitize_path(raw_app)

    assets = []

    # Priority 1: Use session's canonical CryptoAsset collection if available
    from segments.scraping.discovery.models import CryptoAsset
    from segments.reporting.dashboard.views import _asset_risk, _priority_score
    from segments.mitigation.mitigation_agent import rules

    canonical_assets = (
        list(CryptoAsset.objects.using(db).filter(session_id=run.session_id).order_by("id"))
        if run.session_id
        else list(CryptoAsset.objects.using(db).all().order_by("id"))
    )

    from segments.ml.risk_classifier import classify_canonical_asset

    if canonical_assets:
        assessments = list(run.assessments.all())
        for ca in canonical_assets:
            algo_upper = (ca.algorithm or "").upper()
            algo_clean = algo_upper.replace("-", "").replace("_", "")

            if ca.family in ("rsa", "ecc", "dsa", "dh") or any(
                k in algo_clean for k in ("RSA", "ECC", "ECDSA", "ECDH", "ED25519", "DSA", "DH", "X25519")
            ):
                cat = "PUBLIC_KEY"
            elif ca.family in ("aes", "des", "3des") or any(
                k in algo_clean for k in ("AES", "DES", "3DES", "BLOWFISH", "RC4", "CHACHA20")
            ):
                cat = "SYMMETRIC"
            elif ca.family in ("hash",) or any(k in algo_clean for k in ("SHA", "MD5", "HMAC")):
                cat = "HASH"
            else:
                cat = "UNKNOWN"

            role = ""
            loc_lower = (ca.location or ca.source_path or "").lower()
            if "cert" in loc_lower:
                role = "certificate"
            elif algo_upper in ("ECDSA", "ED25519"):
                role = "digital_signature"
            elif algo_upper in ("ECDH", "X25519", "DH") or "RSA" in algo_upper:
                role = "key_establishment"
            elif "test_crypto_example" in loc_lower:
                role = "password_hashing"

            # Aggregate findings and assessments for this canonical asset
            matching_assessments = []
            for a in assessments:
                cb = a.cbom_asset or {}
                if (
                    (cb.get("algorithm") or "").upper() == algo_upper
                    or cb.get("location", {}).get("file") == (ca.location or ca.source_path)
                    or (a.asset_id and a.asset_id == ca.pk)
                ):
                    matching_assessments.append(a)

            # Aggregate operational exposure and HNDL signals
            any_public = bool(
                "public" in loc_lower
                or "external" in loc_lower
                or str(getattr(ca, "environment", "")).lower() in ("public", "external", "internet", "internet-facing")
                or any(
                    (a.cbom_asset or {}).get("internet_facing")
                    or (a.cbom_asset or {}).get("public_endpoint")
                    or str((a.cbom_asset or {}).get("exposure") or "").lower() in ("public", "external", "internet", "internet-facing")
                    for a in matching_assessments
                )
            )

            # Extract strongest HNDL exposure
            hndl_val = "HIGH" if "cert" in loc_lower else ""
            hndl_dict = {}
            mosca_dict = {}
            for a in matching_assessments:
                if a.hndl_result and not hndl_dict:
                    hndl_dict = a.hndl_result
                    r = _hndl_risk(a)
                    if r and r not in ("NOT_ASSESSABLE", "UNKNOWN"):
                        hndl_val = r
                if a.mosca_result and not mosca_dict:
                    mosca_dict = a.mosca_result

            # Extract Mosca parameters
            mosca_body = mosca_dict.get("mosca_assessment") or {}
            mosca_params = mosca_body.get("mosca_parameters") or {}

            # Also inspect linked normalized findings for explicit operational metadata
            try:
                for norm in ca.normalized_findings.all():
                    ev = norm.evidence or {}
                    if ev.get("hndl_exposure"):
                        hndl_val = str(ev["hndl_exposure"]).upper()
                    if ev.get("public_endpoint") or ev.get("internet_facing") or str(ev.get("exposure") or "").lower() in ("public", "external", "internet", "internet-facing"):
                        any_public = True
                    if ev.get("data_shelf_life_years") and not mosca_params.get("y_shelf_life"):
                        try:
                            mosca_params["y_shelf_life"] = float(ev["data_shelf_life_years"])
                        except (ValueError, TypeError):
                            pass
                    if ev.get("migration_time_years") and not mosca_params.get("x_migration_time"):
                        try:
                            mosca_params["x_migration_time"] = float(ev["migration_time_years"])
                        except (ValueError, TypeError):
                            pass
                    if ev.get("role"):
                        role = ev["role"]
                    if ev.get("exploitability_score") and not getattr(ca, "exploitability_score", None):
                        try:
                            ca.exploitability_score = float(ev["exploitability_score"])
                        except (ValueError, TypeError):
                            pass
            except Exception:
                pass

            cls_input = {
                "algorithm": ca.algorithm,
                "family": ca.family,
                "key_size": ca.key_size,
                "role": role or cat,
                "network_exposure": "public" if any_public else "internal",
                "internet_facing": any_public,
                "hndl_risk": hndl_val,
                "migration_time_years": mosca_params.get("x_migration_time"),
                "data_shelf_life_years": mosca_params.get("y_shelf_life"),
                "mosca_at_risk": mosca_body.get("mosca_at_risk") or (float(mosca_body.get("timeline_deficit_years", 0.0)) > 0),
                "mosca_status": mosca_body.get("mosca_status"),
                "exploitability_score": getattr(ca, "exploitability_score", None),
            }
            cls_res = classify_canonical_asset(cls_input)

            cbom = {
                "asset_id": ca.name,
                "name": ca.name,
                "algorithm": ca.algorithm,
                "family": ca.family,
                "location": {"file": _sanitize_path(ca.location or ca.source_path)},
                "parameters": {"key_size": ca.key_size, "curve": ca.curve},
                "crypto_role": role,
            }

            assets.append(
                {
                    "id": f"asset-{ca.pk}",
                    "asset_id": ca.name,
                    "algorithm": ca.algorithm,
                    "family": ca.family,
                    "algorithm_category": cat,
                    "classical_security": cls_res["classical_security"],
                    "overall_risk": cls_res["risk_tier"],
                    "migration_priority": cls_res["priority"],
                    "quantum_vulnerable": cls_res["quantum_vulnerable"],
                    "hndl_risk": hndl_val or cls_res["hndl_exposure"],
                    "remediation_wave": cls_res["remediation_wave"],
                    "urgency_reason": cls_res["urgency_reason"],
                    "service": rules.service_for_location(ca.location or ca.source_path),
                    "cbom_asset": cbom,
                    "mosca": mosca_dict,
                    "hndl": hndl_dict,
                    "crypto_role": role,
                }
            )
    else:
        assessments = list(run.assessments.all())
        for a in assessments:
            cbom = a.cbom_asset or {}
            cbom_id = str(cbom.get("asset_id") or "")
            fallback_id = str(a.finding_ref or "")
            ex = row_by_asset.get(cbom_id) or row_by_asset.get(fallback_id) or {}
            asset_id = cbom_id or ex.get("asset_id") or fallback_id
            ctx_key = asset_id or f"assessment-{a.pk}"
            assets.append(
                {
                    "id": ctx_key,
                    "asset_id": asset_id,
                    "algorithm": ex.get("algorithm") or cbom.get("algorithm"),
                    "family": ex.get("family") or cbom.get("family") or "",
                    "algorithm_category": ex.get("algorithm_category")
                    or _mosca_field(a, "algorithm_category")
                    or "UNKNOWN",
                    "classical_security": ex.get("classical_security")
                    or _mosca_field(a, "classical_security")
                    or "",
                    "overall_risk": ex.get("overall_risk")
                    or _mosca_field(a, "overall_risk")
                    or "",
                    "migration_priority": ex.get("migration_priority")
                    or _mosca_field(a, "migration_priority")
                    or "",
                    "quantum_vulnerable": _first_not_none(
                        ex.get("quantum_vulnerable"), _mosca_field(a, "quantum_vulnerable")
                    ),
                    "hndl_risk": ex.get("hndl_risk") or _hndl_risk(a),
                    "cbom_asset": cbom,
                    "mosca": a.mosca_result or {},
                    "hndl": a.hndl_result or {},
                }
            )

    # A completed run normally has assessments; fall back to the executive
    # summary alone so the plan still renders in degraded states.
    if not assets:
        for ex in rows:
            ctx_key = str(ex.get("asset_id") or "")
            if not ctx_key:
                continue
            assets.append(
                {
                    "id": ctx_key,
                    "asset_id": ctx_key,
                    "algorithm": ex.get("algorithm"),
                    "family": ex.get("family") or "",
                    "algorithm_category": ex.get("algorithm_category") or "UNKNOWN",
                    "classical_security": ex.get("classical_security") or "",
                    "overall_risk": ex.get("overall_risk") or "",
                    "migration_priority": ex.get("migration_priority") or "",
                    "quantum_vulnerable": ex.get("quantum_vulnerable"),
                    "hndl_risk": ex.get("hndl_risk") or "",
                    "cbom_asset": {},
                    "mosca": {},
                    "hndl": {},
                }
            )

    return {
        "application": app_name,
        "repository": repository,
        "risk_context": risk_ctx,
        "assets": assets,
    }


def _mosca_field(assessment, key):
    mosca = (assessment.mosca_result or {}).get("mosca_assessment") or {}
    return mosca.get(key)


def _hndl_risk(assessment):
    hndl = (assessment.hndl_result or {}).get("hndl") or {}
    value = hndl.get("future_decryption_risk")
    if value:
        return value
    if hndl.get("applicable"):
        return hndl.get("risk") or hndl.get("exposure") or ""
    return ""


def _first_not_none(*values):
    for value in values:
        if value is not None:
            return value
    return None


@db_task()
def generate_plan_task(plan_id, mode):
    """Thin huey task wrapper around generate_plan; never crashes the worker."""
    try:
        generate_plan(plan_id, mode)
    except Exception as exc:  # noqa: BLE001 - worker must survive unexpected errors
        logger.exception("generate_plan_task: plan %s crashed: %s", plan_id, exc)