"""Generate the ECDAT schema-visibility artifacts.

Introspects the installed Django apps and emits:

  docs/architecture/schema-ownership.md   table -> owning segment matrix
  docs/architecture/ecdat-erd.md          Mermaid erDiagram (renders on GitHub)

Run (from the repo root, venv active):
    python scripts/generate_schema_docs.py

Both files are AUTO-GENERATED. Do not edit them by hand; edit this script and
regenerate instead.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")

import django  # noqa: E402

django.setup()

from django.apps import apps  # noqa: E402
from django.db import models  # noqa: E402

# app_label -> business segment (kept in sync with config/settings.py).
APP_SEGMENT = {
    "core": "shared (top-level `core/`)",
    "discovery": "scraping (`segments/scraping/discovery/`)",
    "crypto_scan": "scraping (`segments/scraping/crypto_scan/`)",
    "analysis": "ml (`segments/ml/analysis/`)",
    "mitigation": "mitigation (`segments/mitigation/mitigation/`)",
    "dashboard": "reporting (`segments/reporting/dashboard/`)",
    "reports": "reporting (`segments/reporting/reports/`)",
}

OWNED_APPS = [a for a in apps.get_app_configs() if a.label in APP_SEGMENT]
MODELS = sorted(
    (m for a in OWNED_APPS for m in a.get_models()),
    key=lambda m: (APP_SEGMENT[m._meta.app_label], m._meta.app_label, m.__name__),
)

_FIELD_SIMPLE = {"Auto", "BigAuto"}


def _field_type(field: models.Field) -> str:
    t = type(field).__name__
    t = t.removesuffix("Field")
    return t if t not in _FIELD_SIMPLE else "AutoField"


def _is_relation(field: models.Field) -> bool:
    return field.is_relation and not field.auto_created


def _mermaid_name(model) -> str:
    return f"{model._meta.app_label}_{model.__name__.lower()}"


def _local_fields(model):
    for f in model._meta.fields:
        if f.auto_created:
            continue
        yield f


def build_matrix() -> str:
    lines = [
        "# Schema ownership matrix",
        "",
        "> AUTO-GENERATED by `scripts/generate_schema_docs.py` — do not edit; regenerate.",
        "",
        "Every table is owned by exactly one workstream segment. The segment that",
        "scans **writes** a table owns it; downstream segments consume it read-only",
        "through the shared handoff contracts in `schema/contracts/`.",
        "",
        "| Model | Table | App (module) | Segment |",
        "|---|---|---|---|",
    ]
    for m in MODELS:
        app = m._meta.app_label
        lines.append(f"| {m.__name__} | `{m._meta.db_table}` | `{m._meta.app_label}` | {APP_SEGMENT[app]} |")
    lines.append("")
    return "\n".join(lines)


def build_erd() -> str:
    lines = [
        "# ECDAT schema (Mermaid ERD)",
        "",
        "> AUTO-GENERATED by `scripts/generate_schema_docs.py` — do not edit; regenerate.",
        "",
        "Render this file on GitHub (Mermaid) or paste into https://mermaid.live.",
        "",
        "```mermaid",
        "erDiagram",
    ]
    for m in MODELS:
        lines.append(f'    {_mermaid_name(m)} {{')
        for f in _local_fields(m):
            markers = []
            if f.primary_key:
                markers.append("PK")
            if f.unique:
                markers.append("UK")
            if _is_relation(f):
                markers.append("FK")
            tag = " ".join(markers)
            line = _field_type(f) + " " + f.name
            if tag:
                line += ' "{0}"'.format(tag)
            lines.append("        " + line)
        lines.append("    }")
        lines.append("")

    # External models referenced by FKs but not owned by any segment
    # (e.g. django.contrib.auth.User) get a minimal stub so the diagram renders.
    external = set()
    for m in MODELS:
        for f in list(m._meta.fields) + list(m._meta.many_to_many):
            if getattr(f, "related_model", None) and f.related_model not in MODELS:
                external.add(f.related_model)
    for em in sorted(external, key=lambda x: f"{x._meta.app_label}_{x.__name__}"):
        lines.append(f"    {_mermaid_name(em)} {{")
        pk = em._meta.pk
        if pk is not None:
            lines.append(f"        {_field_type(pk)} {pk.name} \"PK\"")
        lines.append("    }")
        lines.append("")

    # Relationships (FK / O2O and many-to-many).
    for m in MODELS:
        a = _mermaid_name(m)
        for f in m._meta.fields:
            if not _is_relation(f) or not f.related_model:
                continue
            b = _mermaid_name(f.related_model)
            if f.many_to_one or f.one_to_one or f.one_to_many:
                card = "||--o{" if f.null else "||--||"
                lines.append(f"    {a} {card} {b} : \"{f.name}\"")
        for f in m._meta.many_to_many:
            if not f.related_model:
                continue
            b = _mermaid_name(f.related_model)
            lines.append(f"    {a} }}o--o{{ {b} : \"{f.name}\"")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    out_dir = ROOT / "docs" / "architecture"
    out_dir.mkdir(parents=True, exist_ok=True)
    (out_dir / "schema-ownership.md").write_text(build_matrix(), encoding="utf-8")
    (out_dir / "ecdat-erd.md").write_text(build_erd(), encoding="utf-8")
    print(f"wrote {out_dir / 'schema-ownership.md'}")
    print(f"wrote {out_dir / 'ecdat-erd.md'}")