# Generated by Django 5.0.7 on 2026-08-30 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scan', '0002_scan_ingested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='session_id',
            field=models.PositiveIntegerField(blank=True, help_text='WorkSession pk (resolved in the active mode DB) that this scan belongs to.', null=True),
        ),
    ]
