# Generated by Django 5.0.7 on 2026-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scan', '0003_scan_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='scanchunk',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
