# Generated by Django 5.0.7 on 2026-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigationplan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16),
        ),
    ]
