# Generated by Django 5.0.7 on 2026-08-30 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('family', models.CharField(choices=[('rsa', 'RSA'), ('ecc', 'ECC'), ('dsa', 'DSA'), ('dh', 'Diffie-Hellman'), ('aes', 'AES'), ('hash', 'Hash'), ('mac', 'MAC'), ('pqc', 'Post-Quantum'), ('unknown', 'Unknown')], max_length=16)),
                ('algorithm', models.CharField(blank=True, default='', max_length=64)),
                ('key_size', models.PositiveIntegerField(blank=True, null=True)),
                ('curve', models.CharField(blank=True, default='', max_length=64)),
                ('protocol', models.CharField(blank=True, default='', max_length=64)),
                ('library', models.CharField(blank=True, default='', max_length=128)),
                ('library_version', models.CharField(blank=True, default='', max_length=64)),
                ('confidence', models.FloatField(default=0.0, help_text='0.0-1.0')),
                ('dedup_key', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('source_code', 'Source Code Repos'), ('binary', 'Binary Files'), ('dependency', 'Libraries/Dependencies'), ('container', 'Container Images'), ('certificate', 'Certificates/PKI'), ('hsm', 'HSM/Key Management'), ('cloud', 'Cloud Crypto Services')], max_length=16)),
                ('location', models.CharField(blank=True, default='', max_length=1024)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('normalized', 'Normalized'), ('ignored', 'Ignored'), ('duplicate', 'Duplicate')], default='new', max_length=16)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-ingested_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('family', models.CharField(choices=[('rsa', 'RSA'), ('ecc', 'ECC'), ('dsa', 'DSA'), ('dh', 'Diffie-Hellman'), ('aes', 'AES'), ('hash', 'Hash'), ('mac', 'MAC'), ('pqc', 'Post-Quantum'), ('unknown', 'Unknown')], max_length=16)),
                ('algorithm', models.CharField(blank=True, default='', max_length=64)),
                ('key_size', models.PositiveIntegerField(blank=True, null=True)),
                ('curve', models.CharField(blank=True, default='', max_length=64)),
                ('protocol', models.CharField(blank=True, default='', max_length=64)),
                ('library', models.CharField(blank=True, default='', max_length=128)),
                ('library_version', models.CharField(blank=True, default='', max_length=64)),
                ('source_type', models.CharField(choices=[('source_code', 'Source Code Repos'), ('binary', 'Binary Files'), ('dependency', 'Libraries/Dependencies'), ('container', 'Container Images'), ('certificate', 'Certificates/PKI'), ('hsm', 'HSM/Key Management'), ('cloud', 'Cloud Crypto Services')], max_length=16)),
                ('location', models.CharField(blank=True, default='', max_length=1024)),
                ('owner', models.CharField(blank=True, default='', max_length=128)),
                ('inventory_status', models.CharField(choices=[('active', 'Active'), ('dormant', 'Dormant'), ('needs_review', 'Needs review')], default='active', max_length=16)),
                ('normalized_findings', models.ManyToManyField(related_name='assets', to='discovery.normalizedfinding')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='normalizedfinding',
            name='raw_finding',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='discovery.rawfinding'),
        ),
        migrations.CreateModel(
            name='ScanJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(choices=[('source_code', 'Source Code Repos'), ('binary', 'Binary Files'), ('dependency', 'Libraries/Dependencies'), ('container', 'Container Images'), ('certificate', 'Certificates/PKI'), ('hsm', 'HSM/Key Management'), ('cloud', 'Cloud Crypto Services')], max_length=16)),
                ('target', models.CharField(help_text='Repo URL, image ref, cert store path, host:port, etc.', max_length=512)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('findings_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'status'], name='discovery_s_source__52e976_idx')],
            },
        ),
        migrations.AddField(
            model_name='rawfinding',
            name='scan_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_findings', to='discovery.scanjob'),
        ),
        migrations.CreateModel(
            name='AssetRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('contains', 'Contains'), ('relate', 'Relates to'), ('context', 'Shares context'), ('depends', 'Depends on')], max_length=16)),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('from_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='discovery.cryptoasset')),
                ('to_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='discovery.cryptoasset')),
            ],
            options={
                'unique_together': {('from_asset', 'to_asset', 'relation_type')},
            },
        ),
        migrations.AddIndex(
            model_name='cryptoasset',
            index=models.Index(fields=['family'], name='discovery_c_family_de762e_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoasset',
            index=models.Index(fields=['source_type'], name='discovery_c_source__f42aa8_idx'),
        ),
        migrations.AddIndex(
            model_name='rawfinding',
            index=models.Index(fields=['source_type', 'status'], name='discovery_r_source__127f77_idx'),
        ),
    ]
