# Generated by Django 5.0.7 on 2026-08-31 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0003_assetrelation_session_cryptoasset_session_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanjob',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=16),
        ),
    ]
