# Generated by Django 5.0.7 on 2026-08-30 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('discovery', '0002_assetrelation_mode_cryptoasset_mode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('repository', models.JSONField(blank=True, default=dict)),
                ('raw_system_context', models.JSONField(blank=True, default=dict)),
                ('input_payload', models.JSONField(blank=True, default=dict)),
                ('cbom_document', models.JSONField(blank=True, default=dict)),
                ('risk_context', models.JSONField(blank=True, default=dict)),
                ('executive_summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('scan_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='discovery.scanjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8)),
                ('finding_ref', models.CharField(blank=True, default='', max_length=128)),
                ('cbom_asset', models.JSONField(blank=True, default=dict)),
                ('hndl_result', models.JSONField(blank=True, default=dict)),
                ('mosca_result', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='discovery.cryptoasset')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='analysis.analysisrun')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['status'], name='analysis_an_status_84ecd1_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['mode'], name='analysis_an_mode_53d302_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassessment',
            index=models.Index(fields=['run'], name='analysis_as_run_id_527a9f_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassessment',
            index=models.Index(fields=['mode'], name='analysis_as_mode_b89e32_idx'),
        ),
        migrations.AddIndex(
            model_name='assetassessment',
            index=models.Index(fields=['finding_ref'], name='analysis_as_finding_979c43_idx'),
        ),
    ]
