# Generated by Django 5.0.7 on 2026-08-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
        ('core', '0003_worksession_auditlog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisrun',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this analysis run belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis_runs', to='core.worksession'),
        ),
        migrations.AddField(
            model_name='assetassessment',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this assessment belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_assessments', to='core.worksession'),
        ),
    ]
