# Generated by Django 5.0.7 on 2026-08-30 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=4096)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete')], default='pending', max_length=16)),
                ('chunk_count', models.PositiveIntegerField(default=0, help_text='Total number of chunks (N).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_id', models.PositiveIntegerField(help_text='0-based chunk index within the scan.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done')], default='pending', max_length=16)),
                ('results', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='crypto_scan.scan')),
            ],
            options={
                'ordering': ['chunk_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='scanchunk',
            constraint=models.UniqueConstraint(fields=('scan', 'chunk_id'), name='uniq_scan_chunk_id'),
        ),
    ]
