# Generated by Django 5.0.7 on 2026-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_scan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='ingested_at',
            field=models.DateTimeField(blank=True, help_text='When the aggregated findings were forwarded into the discovery inventory (null = not yet).', null=True),
        ),
    ]
