# Generated by Django 5.0.7 on 2026-08-31 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analysis', '0003_analysisrun_awaituntil'),
        ('core', '0003_worksession_auditlog_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='MitigationPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('document', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('run', models.OneToOneField(help_text='The completed analysis run this plan is derived from.', on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_plan', to='analysis.analysisrun')),
                ('session', models.ForeignKey(blank=True, help_text='Work session this plan belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mitigation_plans', to='core.worksession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='mitigation__status_bbdccb_idx'), models.Index(fields=['mode'], name='mitigation__mode_1c5c8e_idx')],
            },
        ),
    ]
