"use client";

import { useState } from "react";
import Link from "next/link";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Archive, ArrowDownToLine, FileArchive, FileJson, FileSpreadsheet, FileText, Loader2, RefreshCw, ShieldCheck } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { EmptyState, ErrorState, LoadingState } from "@/components/feedback/data-state";
import { PageHeader, SectionLabel } from "@/components/data/page-header";
import { useToast } from "@/components/feedback/toast";
import { api } from "@/lib/api/client";
import { useSession } from "@/lib/session-context";
import { formatDate, formatNumber, titleCase } from "@/lib/utils";

function saveBlob(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  window.setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function decodeBase64(value: string) {
  const binary = window.atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) bytes[index] = binary.charCodeAt(index);
  return bytes;
}

export default function ReportsPage() {
  const { ready, scopeKey, info } = useSession();
  const { pushToast } = useToast();
  const [busy, setBusy] = useState<string | null>(null);
  const overview = useQuery({ queryKey: ["reports-overview", scopeKey], queryFn: api.reportingOverview, enabled: ready });
  const pipeline = useQuery({ queryKey: ["reports-pipeline", scopeKey], queryFn: api.reportingPipeline, enabled: ready });

  const download = async (path: string, filename: string) => {
    setBusy(path);
    try {
      const blob = await api.reportsBlob(path);
      saveBlob(blob, filename);
      pushToast(`${filename} downloaded.`, "success");
    } catch (error) {
      pushToast(error instanceof Error ? error.message : "Export failed.", "error");
    } finally {
      setBusy(null);
    }
  };

  const generateFull = useMutation({
    mutationFn: api.fullReport,
    onSuccess: (payload) => {
      try {
        const blob = new Blob([decodeBase64(payload.b64)], { type: payload.mime || "application/octet-stream" });
        saveBlob(blob, payload.filename || `ecdat-report.${payload.format || "pdf"}`);
        pushToast(`${payload.filename || "Full report"} generated and downloaded.`, "success");
      } catch (error) {
        pushToast(error instanceof Error ? error.message : "The generated report could not be decoded.", "error");
      }
    },
    onError: (error) => pushToast(error instanceof Error ? error.message : "Full report generation failed.", "error")
  });

  const refresh = () => { void overview.refetch(); void pipeline.refetch(); };

  return (
    <div className="space-y-6">
      <PageHeader eyebrow="Reporting segment" title="Reports & CBOM" description="Export backend-generated snapshots and reports for the active scope. Generation is on demand and uses the local Django service." actions={<Button variant="outline" size="sm" onClick={refresh}><RefreshCw className="h-3.5 w-3.5" aria-hidden="true" />Refresh</Button>} />

      {overview.isLoading ? <LoadingState label="Loading report overview" /> : overview.isError ? <ErrorState message={overview.error instanceof Error ? overview.error.message : undefined} onRetry={() => void overview.refetch()} /> : <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>Estate report readiness</CardTitle><p className="mt-1 text-xs text-muted-foreground">Reporting overview for {info?.session_name || "All data"}.</p></div><FileBarChartIcon /></CardHeader><CardContent className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><ReportMetric label="Assets" value={overview.data?.kpis.assets} /><ReportMetric label="Scans" value={overview.data?.kpis.scans} /><ReportMetric label="Analysed" value={overview.data?.kpis.analysed} /><ReportMetric label="Plans" value={overview.data?.kpis.plan_count} /><ReportMetric label="Generated" value={overview.data?.mitigation_done ? 1 : 0} /></CardContent></Card>}

      <div className="grid gap-4 xl:grid-cols-[1.2fr_0.8fr]"><Card><CardHeader><CardTitle>Export center</CardTitle><p className="mt-1 text-xs leading-5 text-muted-foreground">Downloads are generated by the backend and saved by this browser. No remote storage is required.</p></CardHeader><CardContent className="space-y-3"><ExportRow icon={FileJson} title="Asset snapshot" description="Structured JSON asset inventory." action="assets.json" filename="ecdat-assets.json" onDownload={download} busy={busy} /><ExportRow icon={FileSpreadsheet} title="Raw findings CSV" description="Raw scanner findings with ingestion metadata." action="raw.csv" filename="ecdat-raw.csv" onDownload={download} busy={busy} /><ExportRow icon={FileSpreadsheet} title="Normalized findings CSV" description="Canonical algorithm and library fields." action="normalized.csv" filename="ecdat-normalized.csv" onDownload={download} busy={busy} /><ExportRow icon={Archive} title="Assets CSV" description="Flat asset inventory for downstream workflows." action="assets.csv" filename="ecdat-assets.csv" onDownload={download} busy={busy} /><div className="flex flex-col gap-3 border border-primary/30 bg-primary/5 p-4 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-start gap-3"><FileText className="mt-0.5 h-4 w-4 shrink-0 text-primary" aria-hidden="true" /><div><p className="text-sm font-semibold">Full enterprise report</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Generates a PDF when a local browser is available; otherwise the backend returns an HTML payload and a render warning.</p></div></div><Button onClick={() => generateFull.mutate()} disabled={generateFull.isPending} className="shrink-0">{generateFull.isPending ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" /> : <ArrowDownToLine className="h-3.5 w-3.5" aria-hidden="true" />}Generate report</Button></div>{generateFull.data?.render_error ? <p className="text-xs text-warning">Backend render warning: {generateFull.data.render_error}</p> : null}</CardContent></Card><Card><CardHeader><CardTitle>Discovery pipeline</CardTitle><p className="mt-1 text-xs text-muted-foreground">Backend stage counts for report coverage.</p></CardHeader><CardContent className="p-0">{pipeline.isLoading ? <div className="p-5"><LoadingState label="Loading pipeline" /></div> : pipeline.isError ? <div className="p-5"><ErrorState message={pipeline.error instanceof Error ? pipeline.error.message : undefined} onRetry={() => void pipeline.refetch()} /></div> : pipeline.data?.stages?.length ? <Table><TableHeader><TableRow><TableHead>Stage</TableHead><TableHead>Count</TableHead><TableHead>State</TableHead></TableRow></TableHeader><TableBody>{pipeline.data.stages.map((stage) => <TableRow key={stage.key}><TableCell><p className="font-medium">{stage.name}</p><p className="mt-0.5 text-[11px] text-muted-foreground">{stage.detail}</p></TableCell><TableCell className="tnum">{formatNumber(stage.count)}</TableCell><TableCell><span className={stage.done ? "text-xs text-success" : "text-xs text-muted-foreground"}>{stage.done ? "Ready" : "No data"}</span></TableCell></TableRow>)}</TableBody></Table> : <div className="p-5"><EmptyState title="Pipeline unavailable" description="The reporting API returned no pipeline stages." /></div>}</CardContent></Card></div>

      <Card><CardHeader className="flex-row items-center justify-between"><div><CardTitle>CBOM access</CardTitle><p className="mt-1 text-xs text-muted-foreground">The current backend returns the custom ECDAT-CBOM document inside analysis detail rather than a dedicated export endpoint.</p></div><ShieldCheck className="h-4 w-4 text-primary" aria-hidden="true" /></CardHeader><CardContent className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-2xl text-sm leading-6 text-muted-foreground">Open a completed analysis run to inspect its CBOM assets, locations, confidence, and validation status. No report is generated until you request one.</p><Link href="/analysis" className={buttonVariants({ variant: "outline", size: "sm" })}>Open analysis <ArrowDownToLine className="h-3.5 w-3.5" aria-hidden="true" /></Link></CardContent></Card>
    </div>
  );
}

function ReportMetric({ label, value }: { label: string; value?: number }) { return <div className="border p-4"><p className="text-[10px] font-semibold uppercase tracking-[0.12em] text-muted-foreground">{label}</p><p className="tnum mt-3 text-2xl font-semibold">{formatNumber(value)}</p></div>; }
function FileBarChartIcon() { return <FileText className="h-4 w-4 text-muted-foreground" aria-hidden="true" />; }

function ExportRow({ icon: Icon, title, description, action, filename, onDownload, busy }: { icon: typeof FileJson; title: string; description: string; action: string; filename: string; onDownload: (action: string, filename: string) => Promise<void>; busy: string | null }) {
  return <div className="flex flex-col gap-3 border p-4 sm:flex-row sm:items-center"><div className="flex min-w-0 flex-1 items-start gap-3"><Icon className="mt-0.5 h-4 w-4 shrink-0 text-muted-foreground" aria-hidden="true" /><div><p className="text-sm font-semibold">{title}</p><p className="mt-1 text-xs text-muted-foreground">{description}</p></div></div><Button variant="outline" size="sm" onClick={() => void onDownload(`/reports/${action}`, filename)} disabled={busy === `/reports/${action}`}>{busy === `/reports/${action}` ? <Loader2 className="h-3.5 w-3.5 animate-spin" aria-hidden="true" /> : <ArrowDownToLine className="h-3.5 w-3.5" aria-hidden="true" />}Download</Button></div>;
}
