# Generated by Django 5.0.7 on 2026-08-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8),
        ),
        migrations.AddField(
            model_name='normalizedfinding',
            name='mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8),
        ),
        migrations.AddField(
            model_name='rawfinding',
            name='mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='mode',
            field=models.CharField(choices=[('demo', 'Demo'), ('actual', 'Actual')], default='actual', max_length=8),
        ),
        migrations.AddIndex(
            model_name='rawfinding',
            index=models.Index(fields=['mode'], name='discovery_r_mode_f249cb_idx'),
        ),
        migrations.AddIndex(
            model_name='scanjob',
            index=models.Index(fields=['mode'], name='discovery_s_mode_a59763_idx'),
        ),
    ]
