# Generated by Django 5.0.7 on 2026-08-30 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_worksession_auditlog_session'),
        ('discovery', '0002_assetrelation_mode_cryptoasset_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetrelation',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this relation belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_relations', to='core.worksession'),
        ),
        migrations.AddField(
            model_name='cryptoasset',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this asset belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crypto_assets', to='core.worksession'),
        ),
        migrations.AddField(
            model_name='normalizedfinding',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this finding belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='normalized_findings', to='core.worksession'),
        ),
        migrations.AddField(
            model_name='rawfinding',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this finding belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='raw_findings', to='core.worksession'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Work session this scan belongs to (null = global).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_jobs', to='core.worksession'),
        ),
    ]
