# Generated by Django 5.0.7 on 2026-09-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_worksession_auditlog_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prefix', models.CharField(db_index=True, max_length=16, unique=True)),
                ('hashed_key', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('scopes', models.CharField(blank=True, default='', help_text='Optional comma-separated scope list (empty = full access).', max_length=255)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'API key',
                'verbose_name_plural': 'API keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
