# Generated by Django 5.0.7 on 2026-09-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auditlog_append_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('scan_created', 'Scan created'), ('scan_completed', 'Scan completed'), ('findings_ingested', 'Findings ingested'), ('asset_merged', 'Asset merged'), ('asset_deleted', 'Asset deleted'), ('scan_deleted', 'Scan deleted'), ('export', 'Export generated'), ('demo_seeded', 'Demo data seeded'), ('system', 'System event')], max_length=32),
        ),
    ]
